//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synera_Addin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synera_Addin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a output .
        /// </summary>
        public static string F3DOutputBodyOrAssembliesDescription {
            get {
                return ResourceManager.GetString("F3DOutputBodyOrAssembliesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body or Assemblies.
        /// </summary>
        public static string F3DOutputBodyOrAssembliesName {
            get {
                return ResourceManager.GetString("F3DOutputBodyOrAssembliesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string F3DOutputDescription {
            get {
                return ResourceManager.GetString("F3DOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is input.
        /// </summary>
        public static string F3DOutputFileNameDescription {
            get {
                return ResourceManager.GetString("F3DOutputFileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string F3DOutputFileNameName {
            get {
                return ResourceManager.GetString("F3DOutputFileNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string F3DOutputKeywords {
            get {
                return ResourceManager.GetString("F3DOutputKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3DOutput.
        /// </summary>
        public static string F3DOutputName {
            get {
                return ResourceManager.GetString("F3DOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import the data from fusion file.
        /// </summary>
        public static string Fusion_360Description {
            get {
                return ResourceManager.GetString("Fusion_360Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string Fusion_360Input1Description {
            get {
                return ResourceManager.GetString("Fusion_360Input1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input 1.
        /// </summary>
        public static string Fusion_360Input1Name {
            get {
                return ResourceManager.GetString("Fusion_360Input1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Fusion_360Keywords {
            get {
                return ResourceManager.GetString("Fusion_360Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion_360.
        /// </summary>
        public static string Fusion_360Name {
            get {
                return ResourceManager.GetString("Fusion_360Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string Fusion_360Output1Description {
            get {
                return ResourceManager.GetString("Fusion_360Output1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output 1.
        /// </summary>
        public static string Fusion_360Output1Name {
            get {
                return ResourceManager.GetString("Fusion_360Output1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Fusion Files.
        /// </summary>
        public static string Fusion2Description {
            get {
                return ResourceManager.GetString("Fusion2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string Fusion2Input1Description {
            get {
                return ResourceManager.GetString("Fusion2Input1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input 1.
        /// </summary>
        public static string Fusion2Input1Name {
            get {
                return ResourceManager.GetString("Fusion2Input1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion.
        /// </summary>
        public static string Fusion2Keywords {
            get {
                return ResourceManager.GetString("Fusion2Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion2.
        /// </summary>
        public static string Fusion2Name {
            get {
                return ResourceManager.GetString("Fusion2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string Fusion2Output1Description {
            get {
                return ResourceManager.GetString("Fusion2Output1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output 1.
        /// </summary>
        public static string Fusion2Output1Name {
            get {
                return ResourceManager.GetString("Fusion2Output1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string SmileyFaceContainerDescription {
            get {
                return ResourceManager.GetString("SmileyFaceContainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string SmileyFaceContainerInput1Description {
            get {
                return ResourceManager.GetString("SmileyFaceContainerInput1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input 1.
        /// </summary>
        public static string SmileyFaceContainerInput1Name {
            get {
                return ResourceManager.GetString("SmileyFaceContainerInput1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SmileyFaceContainerKeywords {
            get {
                return ResourceManager.GetString("SmileyFaceContainerKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmileyFaceContainer.
        /// </summary>
        public static string SmileyFaceContainerName {
            get {
                return ResourceManager.GetString("SmileyFaceContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description..
        /// </summary>
        public static string SmileyFaceContainerOutput1Description {
            get {
                return ResourceManager.GetString("SmileyFaceContainerOutput1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output 1.
        /// </summary>
        public static string SmileyFaceContainerOutput1Name {
            get {
                return ResourceManager.GetString("SmileyFaceContainerOutput1Name", resourceCulture);
            }
        }
    }
}
